name: Build, Test, Publish
on:
  - push

jobs:
  build:
    name: Build and Test
    runs-on: [ self-hosted, macos, dotnet ]
    env:
      DOTNET_NOLOGO: true
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
    defaults:
      run:
        working-directory: src

    outputs:
      is-release: ${{ steps.get-version.outputs.is-release }}
      version: ${{ steps.get-version.outputs.version }}
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set version
        uses: triaxis-oss/dotnet-set-version@v1
        id: get-version
        with:
          project: src/triaxis.Common.BluetoothLE/triaxis.Common.BluetoothLE.props

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build Release
        if: steps.get-version.outputs.is-release == 'true'
        run: |
          msbuild triaxis.Xamarin.BluetoothLE /t:build "/p:Configuration=Release;ContinuousIntegrationBuild=true;DeterministicSourcePaths=true;PackageOutputPath=../packages" /m
          dotnet build triaxis.Maui.BluetoothLE -c Release "/p:ContinuousIntegrationBuild=true;DeterministicSourcePaths=true;PackageOutputPath=../packages"

      - name: Build Development
        if: steps.get-version.outputs.is-release != 'true'
        run: |
          msbuild triaxis.Xamarin.BluetoothLE /t:build "/p:Configuration=Release;ContinuousIntegrationBuild=true;DeterministicSourcePaths=true;IncludeSymbolsInNuget=true;PackageOutputPath=../packages" /m
          dotnet build triaxis.Maui.BluetoothLE -c Release "/p:ContinuousIntegrationBuild=true;DeterministicSourcePaths=true;IncludeSymbolsInNuget=true;PackageOutputPath=../packages"

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: src/packages/*nupkg

      - name: Test
        run: dotnet test triaxis.Xamarin.BluetoothLE.Tests -c Release -v Normal -l "junit;logFilePath=test-results.xml"

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: src/**/test-results.xml

  publish-test-results:
    name: Publish test results
    runs-on: [ self-hosted, macos, dotnet ]
    needs: build
    steps:
      - name: Fetch Test Artifacts
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: ${{runner.temp}}/res

      - name: Publish Test Results
        uses: enricomi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: ${{runner.temp}}/res/**/test-results.xml

  publish-nuget:
    name: Publish NuGet
    runs-on: [ self-hosted, macos, dotnet ]
    env:
      DOTNET_NOLOGO: true
    needs: build

    steps:
      - name: Fetch Package Artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: ${{runner.temp}}/packages

      - name: Publish NuGet Packages
        if: needs.build.outputs.is-release == 'true'
        run: dotnet nuget push ${{runner.temp}}/packages/*.nupkg -s nuget.org -k ${{secrets.NUGET_API_KEY}} --skip-duplicate

      - name: Publish GitHub Packages
        if: needs.build.outputs.is-release != 'true'
        run: dotnet nuget push ${{runner.temp}}/packages/*.nupkg -s https://${{github.actor}}@nuget.pkg.github.com/${{github.repository_owner}} -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
