name: Build, Test, Publish
on:
  - push

defaults:
  run:
    working-directory: src

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true

    steps:
      - uses: actions/checkout@v2

      - run: dotnet restore
      - run: msbuild /t:build /p:Configuration=Release
      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: src/triaxis.Xamarin.BluetoothLE/bin/Release/*nupkg
      - run: dotnet test --no-build -c Release -v Normal -l "junit;logFilePath=test-results.xml"
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: src/**/test-results.xml

  publish-test-results:
    name: Publish test results
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-results
      - uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:latest
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '**/test-results.xml'  

  publish-nuget:
    name: Publish NuGet
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: true
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: packages
          path: src
      - run: dotnet nuget push *.nupkg -s nuget.org -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
        